### ISSUE TITLE
Machines start early

### ISSUE THREAD

**Issue by requiemmg** [IngmarStein/mielesolar#30]
Hi again,

normally, machines used to atart when there was an excees power of x Watts. Now with my current setup and the current version, machines start when the solar production reaches value x, not regarding house consumption                                 

```
Jul 23 08:01:42 RaspberryPi mielesolar[30476]: 2023/07/23 08:01:42 Inverter DC Power: 129
Jul 23 08:01:42 RaspberryPi mielesolar[30476]: 2023/07/23 08:01:42 Inverter AC Power: 127
Jul 23 08:01:42 RaspberryPi mielesolar[30476]: 2023/07/23 08:01:42 Meter AC Power: 783.00
Jul 23 08:01:42 RaspberryPi mielesolar[30476]: 2023/07/23 08:01:42 Battery Power: 0.000000
Jul 23 08:01:47 RaspberryPi mielesolar[30476]: 2023/07/23 08:01:47 Inverter DC Power: 129
Jul 23 08:01:47 RaspberryPi mielesolar[30476]: 2023/07/23 08:01:47 Inverter AC Power: 127
Jul 23 08:01:47 RaspberryPi mielesolar[30476]: 2023/07/23 08:01:47 Meter AC Power: 805.00
Jul 23 08:01:47 RaspberryPi mielesolar[30476]: 2023/07/23 08:01:47 Battery Power: 0.000000
Jul 23 08:01:47 RaspberryPi mielesolar[30476]: 2023/07/23 08:01:47 starting device  (0001
Jul 23 08:01:47 RaspberryPi mielesolar[30476]: 2023/07/23 08:01:47 started device  (00017
```

**Comment by requiemmg** [comment]
Sorry for the bad formatting, that was from my cellphone...
Not quite right what I said, just put my dishwasher to smartstart and solar production is at 1 kW, House consumption at about 1kW, machine is waiting. But yesterday's start was definitely too early and I'm not really sure why.

```
pi@RaspberryPi:~ $ sudo systemctl status mielesolar
● mielesolar.service - Mielesolar
     Loaded: loaded (/lib/systemd/system/mielesolar.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2023-07-21 16:56:36 CEST; 2 days ago
   Main PID: 30476 (mielesolar)
      Tasks: 9 (limit: 2057)
        CPU: 7min 16.201s
     CGroup: /system.slice/mielesolar.service
             └─30476 /usr/local/go/src/mielesolar/mielesolar -user <redacted>

Jul 24 11:40:32 RaspberryPi mielesolar[30476]: 2023/07/24 11:40:32 Meter AC Power: 23.000000
Jul 24 11:40:32 RaspberryPi mielesolar[30476]: 2023/07/24 11:40:32 Battery Power: 148.000000
Jul 24 11:40:37 RaspberryPi mielesolar[30476]: 2023/07/24 11:40:37 Inverter DC Power: 971.800000
Jul 24 11:40:37 RaspberryPi mielesolar[30476]: 2023/07/24 11:40:37 Inverter AC Power: 957.200000
Jul 24 11:40:37 RaspberryPi mielesolar[30476]: 2023/07/24 11:40:37 Meter AC Power: -20.000000
Jul 24 11:40:37 RaspberryPi mielesolar[30476]: 2023/07/24 11:40:37 Battery Power: 196.000000
Jul 24 11:40:42 RaspberryPi mielesolar[30476]: 2023/07/24 11:40:42 Inverter DC Power: 981.000000
Jul 24 11:40:42 RaspberryPi mielesolar[30476]: 2023/07/24 11:40:42 Inverter AC Power: 966.300000
Jul 24 11:40:42 RaspberryPi mielesolar[30476]: 2023/07/24 11:40:42 Meter AC Power: 16.000000
Jul 24 11:40:42 RaspberryPi mielesolar[30476]: 2023/07/24 11:40:42 Battery Power: 202.000000
```

**Comment by IngmarStein** [comment]
I'm back from vacation.

The verbose output of these four values is meant to debug cases like this.
Inverter DC power = DC power coming into the inverter (production)
Inverter AC power = AC power provided by the inverter (after conversion loss)
Meter AC power = balance of production and consumption
Battery power = battery charge (positive) or discharge (negative) rate

The inverter data is informative only and does not go into the decision when to start appliances.

The power export is computed as meter AC power + battery power so that appliances are prioritized higher than charging the battery.

Is the log from Jul 23 complete? These values don't appear plausible:

Inverter DC Power: 129
Inverter AC Power: 127
Meter AC Power: 805.00
Battery Power: 0.000000

Higher balance than production without a discharging battery?

**Comment by requiemmg** [comment]
Cant tell anymore, currently everything working fine. No idea. I will keep track of it.
